[workspace]
members = [
  "jormungandr-lib",
  "jormungandr",
  "jcli",
  "modules/settings",
  "modules/blockchain",
  "modules/clock",
  "modules/kms",
  "modules/mempool",
  "modules/leadership",
  "testing/jormungandr-testing-utils",
  "testing/jormungandr-integration-tests",
  "testing/jormungandr-scenario-tests",
]

exclude = [
  "chain-deps",
]
