[workspace]
members = [
  "jormungandr-lib",
  "jormungandr",
  "jcli",
  "modules/settings",
  "modules/blockchain",
  "explorer",
  "testing/jormungandr-testing-utils",
  "testing/jormungandr-integration-tests",
  "testing/jormungandr-scenario-tests",
]

exclude = [
  "chain-deps",
  "testing/iapyx",
]
