[workspace]
members = [
    "cryptoxide",
    "cardano",
    "wallet-cli",
    "protocol",
    "storage",
    "hermes",
    "cbor_event",
    "cardano-c",
]
[dependencies]
printer = { path = "rust-crypto-wasm" }
