[workspace]
members = [
    "imhamt",
    "chain-core",
    "chain-addr",
    "chain-time",
    "chain-crypto",
    "chain-storage",
    "chain-storage-sqlite",
    "chain-impl-mockchain",
    "cardano",
    "network-core",
    "network-grpc",
    "network-ntt",
    "protocol",
    "protocol-tokio",
    "storage-units",
    "storage",
    "cardano-c",
    "exe-common",
]
