[package]
name = "mjolnir"
version = "0.1.0"
authors = ["Alexander Vershilov <alexander.vershilov@tweag.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
cfg-if = "0.1.2"
rand = "*"
bech32 = "0.6"
cardano = { path = "../../cardano-deps/cardano" }
chain-addr = { path = "../../cardano-deps/chain-addr" }
chain-core = { path = "../../cardano-deps/chain-core" }
chain-crypto = { path = "../../cardano-deps/chain-crypto" }
chain-impl-mockchain = { path = "../../cardano-deps/chain-impl-mockchain" }
hex = { path = "../../hex" }
serde = "^1.0.59"
serde_derive = "^1.0.59"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.1", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.2", optional = true }

[dependencies.wasm-bindgen]
version = "^0.2"
features = ["serde-serialize"]

[dependencies.clear_on_drop]
version = "*"
features = ["no_cc"]

[dev-dependencies]
wasm-bindgen-test = "0.2"



[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
