[package]
name = "jormungandr-integration-tests"
version = "0.9.0-nightly"
authors = [ "dev@iohk.io" ]
edition = "2018"

[dependencies]
grpc            = "0.6.1"
protobuf        = "=2.8.2"
futures         = "~0.1"
futures-cpupool = "~0.1"
base64 = "0.12.0"
bytes = "0.4"
hex = "0.4.2"
chain-addr      = { path = "../../chain-deps/chain-addr" }
chain-core      = { path = "../../chain-deps/chain-core" }
chain-crypto    = { path = "../../chain-deps/chain-crypto" }
chain-impl-mockchain = { path = "../../chain-deps/chain-impl-mockchain" }
chain-storage   = { path = "../../chain-deps/chain-storage" }
chain-time      = { path = "../../chain-deps/chain-time" }
file_diff = "1.0.0"
jormungandr-lib = { path = "../../jormungandr-lib" }
jormungandr-testing-utils = { path = "../jormungandr-testing-utils" }
rand = "0.7"
rand_core = "0.5"
rand_chacha = "0.2"
slog = { version = "^2.5.1", features = [ "max_level_trace", "release_max_level_trace" ] }
slog-async = "2.5.0"
slog-json = "2.3.0"
slog-scope = "4.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
lazy_static = "1.3"
mktemp = "0.4.0"
regex = "1.3"
error-chain = "0.12"
jormungandr = { path = "../../jormungandr" }
jcli = { path = "../../jcli" }
poldercast = "0.13.1"
thiserror = "1.0"
url = "2.1.1"

[target.'cfg(not(target_os = "android"))'.dependencies.reqwest]
version = "0.10.4"
default-features = false
features = ["blocking", "json", "rustls-tls"]

# rustls-native-certs required by rustls-tls does not support Android, so build
# with OpenSSL.
# TODO rustls-tls should work on Android when https://github.com/seanmonstar/reqwest/pull/862
# is merged and released.
[target.'cfg(target_os = "android")'.dependencies.reqwest]
version = "0.10.4"
features = ["blocking", "json"]

[dev-dependencies]
chain-core           = { path = "../../chain-deps/chain-core", features=["property-test-api"]}
chain-crypto         = { path = "../../chain-deps/chain-crypto", features=["property-test-api"] }
chain-addr           = { path = "../../chain-deps/chain-addr", features=["property-test-api"] }
chain-impl-mockchain = { path = "../../chain-deps/chain-impl-mockchain", features=["property-test-api"] }
jormungandr-lib = { path = "../../jormungandr-lib" }
regex = "1.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
quickcheck = "0.9"
galvanic-test = "0.2.0"
assert_cmd = "1.0"
assert_fs = "1.0"
mktemp = "0.4.0"
lazy_static = "1.3"
ed25519-bip32 = "0.3"

[features]
testnet = []
sanity-non-functional = []
soak-non-functional = []

[build-dependencies]
protoc-rust = "2.0"
