[package]
name = "jormungandr-integration-tests"
version = "0.13.0"
authors = [ "dev@iohk.io" ]
edition = "2018"

[dependencies]
tonic = "0.6"
bech32 = "0.7"
prost = "0.9"
tokio = { version = "1.4", features = ["macros", "time"] }
futures      = "0.3.18"
base64 = "0.13"
hex = "0.4.2"
chain-addr      = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "fix-evm-transaction" }
chain-core      = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "fix-evm-transaction" }
chain-crypto    = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "fix-evm-transaction" }
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "fix-evm-transaction" }
chain-time      = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "fix-evm-transaction" }
chain-vote      = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "fix-evm-transaction" }
jormungandr-lib = { path = "../../jormungandr-lib" }
hersir = { path = "../hersir" }
loki = { path = "../loki" }
mjolnir = { path = "../mjolnir" }
jormungandr-testing-utils = { path = "../jormungandr-testing-utils" }
jortestkit = { git = "https://github.com/input-output-hk/jortestkit.git", branch = "master" }
rand = "0.8"
rand_core = "0.6"
rand_chacha = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
lazy_static = "1.4"
assert_fs = "1.0"
predicates = "2.0"
assert_cmd = "1.0.7"
regex = "1.4"
poldercast = "1.2"
thiserror = "1.0"
url = "2.2.0"
yaml-rust = "0.4.4"
indicatif = "0.15.0"
fs_extra = "1.1.0"
tempfile = "3"
json = "0.12.4"
multiaddr = { package = "parity-multiaddr", version = "0.11" }
rstest = "0.12.0"
tracing = "0.1"
function_name = "0.2.0"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking", "json", "rustls-tls"]

[features]
testnet = []
network = []
non-functional = []
soak = []
sanity = []
cross-version = []
explorer-schema-gen = []
