[package]
name = "jormungandr-integration-tests"
version = "0.9.0-rc1"
authors = [ "dev@iohk.io" ]
edition = "2018"

[dependencies]
tonic = "0.2"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
futures      = "0.3.5"
base64 = "0.12"
bytes = "0.4"
hex = "0.4.2"
chain-addr      = { path = "../../chain-deps/chain-addr" }
chain-core      = { path = "../../chain-deps/chain-core" }
chain-crypto    = { path = "../../chain-deps/chain-crypto" }
chain-impl-mockchain = { path = "../../chain-deps/chain-impl-mockchain" }
chain-time      = { path = "../../chain-deps/chain-time" }
jormungandr-lib = { path = "../../jormungandr-lib" }
jormungandr-testing-utils = { path = "../jormungandr-testing-utils" }
rand = "0.7"
rand_core = "0.5"
rand_chacha = "0.2"
slog = { version = "^2.5.1", features = [ "max_level_trace", "release_max_level_trace" ] }
slog-async = "2.5.0"
slog-json = "2.3.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
lazy_static = "1.4"
assert_fs = "1.0"
predicates = "1.0"
regex = "1.3"
poldercast = "0.13.1"
thiserror = "1.0"
url = "2.1.1"
yaml-rust = "0.4.4"

[dependencies.reqwest]
version = "0.10.6"
default-features = false
features = ["blocking", "json", "rustls-tls"]

[features]
testnet = []
sanity-non-functional = []
soak-non-functional = []

[build-dependencies]
tonic-build = "0.2"
