[package]
name = "iapyx"
version = "0.1.0"
authors = ["dkijania <dariusz.kijania@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wallet-core = { git = "https://github.com/input-output-hk/chain-wallet-libs", branch="master"}
wallet = { git = "https://github.com/input-output-hk/chain-wallet-libs", branch="master"}
hex = "0.4"
bip39 = { git = "https://github.com/input-output-hk/chain-wallet-libs", branch="master"}
chain-crypto = { git = "https://github.com/input-output-hk/chain-wallet-libs", branch="master"}
chain-core = { git = "https://github.com/input-output-hk/chain-wallet-libs", branch="master"}
chain-addr = { git = "https://github.com/input-output-hk/chain-wallet-libs", branch="master"}
chain-ser = { git = "https://github.com/input-output-hk/chain-wallet-libs", branch="master"}
hdkeygen = { git = "https://github.com/input-output-hk/chain-wallet-libs", branch="master"}
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-wallet-libs", branch="master"}
rand = "0.7"
rand_core = "0.5"
cryptoxide = "0.2.0"
ed25519-bip32 = "^0.3.1"
jormungandr-testing-utils = { path = "../jormungandr-testing-utils"}
jormungandr-lib = { path = "../../jormungandr-lib" }
jortestkit = { path = "../jortestkit" }
hyper = "0.13.6"
thiserror = "1.0"
serde_json = "1.0.53"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
regex = "*"
dialoguer = "0.6.2"
structopt = "0.3"
console = "0.11"
warp = "0.2.5"
warp-reverse-proxy = "0.1.0"
tokio = { version = "0.2", features = ["macros"] }
url = "2.1.1"

[dependencies.reqwest]
version = "0.10.6"
default-features = false
features = ["blocking"]