[package]
name = "loki"
description = "Loki is a simple command line tool that lets you deploy an adversarial Jormungandr node with a REST interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chain-addr      = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "fix-evm-transaction", features = [ "property-test-api" ] }
chain-crypto    = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "fix-evm-transaction", features = [ "property-test-api" ] }
chain-core      = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "fix-evm-transaction" }
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "fix-evm-transaction" }
jormungandr-testing-utils = { path = "../jormungandr-testing-utils" }
jormungandr-lib = { path = "../../jormungandr-lib" }
tokio = { version = "1.4", features = ["macros","rt","rt-multi-thread"] }
multiaddr = { package = "parity-multiaddr", version = "0.11" }
serde_yaml = "0.8.21"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3.23"
thiserror = "1.0"
warp = "0.3"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking", "json", "rustls-tls"]
