[package]
name = "blockchain"
version = "0.1.0"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>"]
edition = "2018"

[dependencies]
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "add-mint-token-serialize" }
chain-time           = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "add-mint-token-serialize"}
thiserror = "1.0.30"
lru       = "0.6.6"
