[package]
name = "blockchain"
version = "0.1.0"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>"]
edition = "2018"

[dependencies]
chain-impl-mockchain = { path = "../../chain-deps/chain-impl-mockchain" }
chain-time           = { path = "../../chain-deps/chain-time"}
thiserror = "1.0.20"
lru       = "0.5.3"