[package]
name = "hersir"
description = "Hersir is a simple command line tool that lets you deploy a network of Jormungandr nodes"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chain-addr      = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = [ "property-test-api" ] }
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
jormungandr-testing-utils = { path = "../jormungandr-testing-utils" }
jormungandr-lib = { path = "../../jormungandr-lib" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.3.23"
thiserror = "1.0"