[package]
name = "jormungandr-testing-utils"
version = "0.9.1"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.2"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
futures      = "0.3.5"
base64 = "0.12"
bawawa = "0.1.5"
bech32 = "0.7"
bytesize = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chain-impl-mockchain = { path = "../../chain-deps/chain-impl-mockchain", features = [ "property-test-api" ] }
chain-addr      = { path = "../../chain-deps/chain-addr", features = [ "property-test-api" ] }
chain-core      = { path = "../../chain-deps/chain-core" }
chain-crypto    = { path = "../../chain-deps/chain-crypto", features = [ "property-test-api" ] }
chain-time           = { path = "../../chain-deps/chain-time" }
cardano-legacy-address = { path = "../../chain-deps/cardano-legacy-address" }
jormungandr-lib = { path = "../../jormungandr-lib" }
jortestkit = { path = "../jortestkit"}
typed-bytes = { path = "../../chain-deps/typed-bytes" }
rand = "0.7"
rand_core = "0.5"
rand_chacha = "0.2"
chrono = { version = "0.4", features = ["serde"] }
humantime = "2.0"
custom_debug = "0.5"
thiserror = "1.0"
poldercast = "0.13.1"
sysinfo = { version = "0.15.0" }
slog = { version = "^2.5.1", features = [ "max_level_trace", "release_max_level_trace" ] }
slog-async = "2.5.0"
slog-json = "2.3.0"
os_info = { version = "2.0.7", default-features = false }
zip = "0.5.6"
flate2 = "1.0.16"
tar = "0.4"
hex = "0.4"
lazy_static = "1"
serde_derive = "1.0"
assert_fs = "1.0"
serde_yaml = "0.8"
tokio-codec = "0.1"
regex = "1.3"
fs_extra = "1.1.0"
url = "2.1.1"

[dependencies.reqwest]
version = "0.10.7"
default-features = false
features = ["blocking", "json"]

[features]
default = []
property-test-api = [ ]

[build-dependencies]
tonic-build = "0.2"