[package]
name = "jormungandr-testing-utils"
version = "0.9.1-nightly"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bech32 = "0.7"
bytesize = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chain-impl-mockchain = { path = "../../chain-deps/chain-impl-mockchain", features = [ "property-test-api" ] }
chain-addr      = { path = "../../chain-deps/chain-addr", features = [ "property-test-api" ] }
chain-core      = { path = "../../chain-deps/chain-core" }
chain-crypto    = { path = "../../chain-deps/chain-crypto", features = [ "property-test-api" ] }
chain-time           = { path = "../../chain-deps/chain-time" }
cardano-legacy-address = { path = "../../chain-deps/cardano-legacy-address" }
jormungandr-lib = { path = "../../jormungandr-lib" }
typed-bytes = { path = "../../chain-deps/typed-bytes" }
rand = "0.7"
rand_core = "0.5"
rand_chacha = "0.2"
chrono = { version = "0.4", features = ["serde"] }
humantime = "2.0"
custom_debug = "0.5"
thiserror = "1.0"
poldercast = "0.13.1"
sysinfo = { version = "0.14.4" }
os_info = { version = "2.0.6", default-features = false }
zip = "0.5.6"
flate2 = "1.0.14"
tar = "0.4"
hex = "0.4"

[dependencies.reqwest]
version = "0.10.6"
default-features = false
features = ["blocking", "rustls-tls"]

[features]
default = []
property-test-api = [ ]

