[package]
name = "jormungandr-testing-utils"
version = "0.12.0-rc.1"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.4"
prost = "0.7"
tokio = { version = "1.4", features = ["macros","rt","rt-multi-thread"] }
tokio-stream = "0.1"
futures = "0.3.14"
base64 = "0.13"
bech32 = "0.7"
bytesize = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = [ "property-test-api" ] }
chain-addr      = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = [ "property-test-api" ] }
chain-core      = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-crypto    = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = [ "property-test-api" ] }
chain-time      = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-storage   = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = ["with-bench"] }
chain-vote      = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
cardano-legacy-address = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
typed-bytes = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
jormungandr-lib = { path = "../../jormungandr-lib" }
jortestkit = { git = "https://github.com/input-output-hk/jortestkit.git", branch = "master" }
rand = "0.8"
rand_core = "0.6"
rand_chacha = "0.3"
chrono = { version = "0.4", features = ["serde"] }
humantime = "2.0"
custom_debug = "0.5"
thiserror = "1.0"
poldercast = "1.2"
sysinfo = { version = "0.17.0" }
os_info = { version = "3.0.2", default-features = false }
zip = "0.5.6"
flate2 = "1.0.18"
tar = "0.4"
hex = "0.4"
lazy_static = "1"
serde_derive = "1.0"
assert_fs = "1.0"
serde_yaml = "0.8"
regex = "1.4"
fs_extra = "1.1.0"
url = "2.2.0"
graphql_client = "0.9.0"
semver = "0.11.0"
json = "0.12.4"
symmetric-cipher = { git = "https://github.com/input-output-hk/chain-wallet-libs.git", branch = "master" }
qrcodegen = "1.6"
quircs = "0.10.0"
image = "0.23.12"
strum = { version = "0.20", features = ["derive"] }
tracing-subscriber = "0.2"
tracing = "0.1"
netstat2 = "0.9"
multiaddr = { package = "parity-multiaddr", version = "0.11" }
keynesis = "1"
bincode = "1.3"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking", "json", "rustls-tls"]

[features]
default = []
property-test-api = [ ]

[build-dependencies]
tonic-build = "0.4"
