[package]
name = "jormungandr-scenario-tests"
version = "0.10.0-dev"
authors = [ "dev@iohk.io" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = "2"
custom_debug = "0.5"
dialoguer = "0.6.2"
error-chain = "0.12"
assert_fs = "1.0"
chain-core           = { path = "../../chain-deps/chain-core" }
chain-crypto         = { path = "../../chain-deps/chain-crypto", features = [ "property-test-api" ] }
chain-addr           = { path = "../../chain-deps/chain-addr", features = [ "property-test-api" ] }
chain-impl-mockchain = { path = "../../chain-deps/chain-impl-mockchain", features = [ "property-test-api" ] }
chain-time           = { path = "../../chain-deps/chain-time" }
jormungandr-testing-utils = { path = "../jormungandr-testing-utils" }
jormungandr-lib = { path = "../../jormungandr-lib" }
jortestkit = { path = "../jortestkit" }
poldercast = "0.13.1"
rand = "0.7"
rand_core = "0.5"
rand_chacha = "0.2"
regex = "1.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
structopt = "0.3"
thiserror = "1.0"
hex = "0.4"
futures = "0.3.5"
console = "0.11"
yaml-rust = "0.4.4"
indicatif = "0.15"
lazy_static = "1"

[dependencies.reqwest]
version = "0.10.7"
default-features = false
features = ["blocking", "rustls-tls"]
