name: Nix
on:
  push:
    branches:
      - master
      - catalyst-fund*
  pull_request:

jobs:
  build-jormungandr:
    name: Build jormungandr
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/nix-common-setup
      with:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Flake check
      run: nix flake check
    - name: Build
      run: nix build .#jormungandr

  build:
    name: Build ${{ matrix.package }}
    needs: build-jormungandr
    strategy:
      matrix:
        package:
        - "jormungandr-lib"
        - "jcli"
        - "explorer"
        - "modules/settings"
        - "modules/blockchain"
        - "testing/jormungandr-automation"
        - "testing/jormungandr-integration-tests"
        - "testing/loki"
        - "testing/mjolnir"
        - "testing/hersir"
        - "testing/thor"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/nix-common-setup
      with:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Build
      run: nix build .#${{ matrix.package }}
